### ISSUE TITLE
Name conflict

### ISSUE THREAD

**Issue by 8carlosf** [futuo/eva#2]
http://www.gorillatoolkit.org/

Gorilla is a web toolkit for the Go programming language.

**Comment by futuo** [comment]
Hi 8carlosf! Thank you for the heads up! The project was renamed to "eva", much better sounding too =)

**Comment by 8carlosf** [comment]
It does sound better.
Take a look at all of the chapter [Git Internals](https://git-scm.com/book/en/v2/Git-Internals-Plumbing-and-Porcelain)
Even if it doesn't help you directly, it will for sure give you some new ideas.
